# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'child.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(737, 535)
        font = QtGui.QFont()
        font.setPointSize(9)
        Form.setFont(font)
        self.ok_1 = QtWidgets.QPushButton(Form)
        self.ok_1.setGeometry(QtCore.QRect(430, 80, 75, 23))
        self.ok_1.setObjectName("ok_1")
        self.ok_2 = QtWidgets.QPushButton(Form)
        self.ok_2.setGeometry(QtCore.QRect(430, 140, 75, 23))
        self.ok_2.setObjectName("ok_2")
        self.ok_3 = QtWidgets.QPushButton(Form)
        self.ok_3.setGeometry(QtCore.QRect(430, 190, 75, 23))
        self.ok_3.setObjectName("ok_3")
        self.week = QtWidgets.QSpinBox(Form)
        self.week.setGeometry(QtCore.QRect(170, 20, 42, 22))
        self.week.setObjectName("week")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 20, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(60, 140, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(50, 200, 54, 12))
        self.label_4.setObjectName("label_4")
        self.p_1 = QtWidgets.QLineEdit(Form)
        self.p_1.setEnabled(True)
        self.p_1.setGeometry(QtCore.QRect(160, 80, 113, 20))
        self.p_1.setObjectName("p_1")
        self.p_2 = QtWidgets.QLineEdit(Form)
        self.p_2.setGeometry(QtCore.QRect(170, 140, 113, 20))
        self.p_2.setObjectName("p_2")
        self.p_3 = QtWidgets.QLineEdit(Form)
        self.p_3.setGeometry(QtCore.QRect(170, 190, 113, 20))
        self.p_3.setObjectName("p_3")
        self.result = QtWidgets.QLCDNumber(Form)
        self.result.setGeometry(QtCore.QRect(420, 330, 151, 61))
        self.result.setObjectName("result")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(85, 330, 321, 61))
        self.textBrowser.setObjectName("textBrowser")
        self.Reset = QtWidgets.QPushButton(Form)
        self.Reset.setGeometry(QtCore.QRect(540, 20, 75, 23))
        self.Reset.setObjectName("Reset")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ok_1.setText(_translate("Form", "PushButton"))
        self.ok_2.setText(_translate("Form", "PushButton"))
        self.ok_3.setText(_translate("Form", "PushButton"))
        self.label.setText(_translate("Form", "孕期(周)"))
        self.label_2.setText(_translate("Form", "参数一"))
        self.label_3.setText(_translate("Form", "参数二"))
        self.label_4.setText(_translate("Form", "参数三"))
        self.p_1.setText(_translate("Form", "0"))
        self.p_2.setText(_translate("Form", "0"))
        self.p_3.setText(_translate("Form", "0"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">胎儿的体重(kg)约为：</span></p></body></html>"))
        self.Reset.setText(_translate("Form", "Reset"))
