# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'midlife3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(789, 583)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(50, 20, 710, 550))
        self.widget.setStyleSheet("background-color: rgb(104, 104, 104);\n"
"border-radius: 25px;")
        self.widget.setObjectName("widget")
        self.close_2 = QtWidgets.QPushButton(self.widget)
        self.close_2.setGeometry(QtCore.QRect(20, 10, 21, 21))
        self.close_2.setStyleSheet("background-color: #F16C61;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px; ")
        self.close_2.setText("")
        self.close_2.setObjectName("close_2")
        self.ok = QtWidgets.QPushButton(self.widget)
        self.ok.setGeometry(QtCore.QRect(620, 480, 75, 40))
        font = QtGui.QFont()
        font.setFamily("华光胖头鱼_CNKI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ok.setFont(font)
        self.ok.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius: 15px;\n"
"")
        self.ok.setObjectName("ok")
        self.reset = QtWidgets.QPushButton(self.widget)
        self.reset.setGeometry(QtCore.QRect(620, 20, 75, 40))
        font = QtGui.QFont()
        font.setFamily("华光胖头鱼_CNKI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.reset.setFont(font)
        self.reset.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius: 15px;\n"
"")
        self.reset.setObjectName("reset")
        self.lcd2 = QtWidgets.QLCDNumber(self.widget)
        self.lcd2.setGeometry(QtCore.QRect(320, 460, 211, 50))
        self.lcd2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 127);\n"
"border-radius: 25px;\n"
"")
        self.lcd2.setObjectName("lcd2")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setGeometry(QtCore.QRect(130, 60, 151, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius: 15px;\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.rate = QtWidgets.QLineEdit(self.widget)
        self.rate.setGeometry(QtCore.QRect(390, 150, 60, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rate.setFont(font)
        self.rate.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 12.5px;\n"
"")
        self.rate.setObjectName("rate")
        self.lcd1 = QtWidgets.QLCDNumber(self.widget)
        self.lcd1.setGeometry(QtCore.QRect(319, 350, 211, 50))
        self.lcd1.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 127);\n"
"border-radius: 25px;\n"
"")
        self.lcd1.setObjectName("lcd1")
        self.year = QtWidgets.QLineEdit(self.widget)
        self.year.setGeometry(QtCore.QRect(390, 230, 60, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.year.setFont(font)
        self.year.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 12.5px;\n"
"")
        self.year.setObjectName("year")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_4.setGeometry(QtCore.QRect(160, 350, 100, 50))
        self.textBrowser_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 127);\n"
"border-radius: 25px;\n"
"\n"
"")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_5.setGeometry(QtCore.QRect(160, 450, 100, 50))
        self.textBrowser_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 127);\n"
"border-radius: 25px;\n"
"\n"
"")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_2.setGeometry(QtCore.QRect(130, 140, 151, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius: 15px;\n"
"")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.total = QtWidgets.QLineEdit(self.widget)
        self.total.setGeometry(QtCore.QRect(390, 70, 60, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.total.setFont(font)
        self.total.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 12.5px;\n"
"")
        self.total.setObjectName("total")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_3.setGeometry(QtCore.QRect(130, 230, 151, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius: 15px;\n"
"")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 711, 551))
        self.widget_2.setStyleSheet("background-image: url(\'./mid3.png\');\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.widget_2.raise_()
        self.close_2.raise_()
        self.ok.raise_()
        self.reset.raise_()
        self.lcd2.raise_()
        self.textBrowser.raise_()
        self.rate.raise_()
        self.lcd1.raise_()
        self.year.raise_()
        self.textBrowser_4.raise_()
        self.textBrowser_5.raise_()
        self.textBrowser_2.raise_()
        self.total.raise_()
        self.textBrowser_3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "贷款计算器"))
        self.ok.setText(_translate("Form", "计算"))
        self.reset.setText(_translate("Form", "重置"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">贷款金额</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:12pt; font-weight:600;\"><br /></p></body></html>"))
        self.rate.setText(_translate("Form", "4"))
        self.year.setText(_translate("Form", "30"))
        self.textBrowser_4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'楷体\'; font-size:12pt; font-weight:600;\">每月还款</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'楷体\'; font-size:12pt; font-weight:600;\">总利息</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">年利率(%)</span></p></body></html>"))
        self.total.setText(_translate("Form", "7500000"))
        self.textBrowser_3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">贷款期限(年)</span></p></body></html>"))
