# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'old.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(811, 566)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(40, 10, 710, 550))
        self.widget.setStyleSheet("background-color: rgb(104, 104, 104);\n"
"border-radius: 25px;")
        self.widget.setObjectName("widget")
        self.close = QtWidgets.QPushButton(self.widget)
        self.close.setGeometry(QtCore.QRect(10, 10, 21, 21))
        self.close.setStyleSheet("background-color:#F16C61;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px; ")
        self.close.setText("")
        self.close.setObjectName("close")
        self.analysis = QtWidgets.QTextEdit(self.widget)
        self.analysis.setGeometry(QtCore.QRect(160, 400, 351, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.analysis.setFont(font)
        self.analysis.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"border-radius: 30px;\n"
"")
        self.analysis.setObjectName("analysis")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_3.setGeometry(QtCore.QRect(170, 320, 121, 41))
        self.textBrowser_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 127);\n"
"border-radius: 20px;\n"
"")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.weight = QtWidgets.QLineEdit(self.widget)
        self.weight.setGeometry(QtCore.QRect(380, 200, 75, 30))
        self.weight.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 170, 127);\n"
"border-radius: 15px;\n"
"")
        self.weight.setObjectName("weight")
        self.lcd = QtWidgets.QLCDNumber(self.widget)
        self.lcd.setGeometry(QtCore.QRect(370, 320, 100, 40))
        self.lcd.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 127);\n"
"border-radius: 20px;\n"
"")
        self.lcd.setObjectName("lcd")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setGeometry(QtCore.QRect(170, 120, 121, 41))
        self.textBrowser.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #FE9A12;\n"
"border-radius: 15px;\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.reset = QtWidgets.QPushButton(self.widget)
        self.reset.setGeometry(QtCore.QRect(600, 70, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.reset.setFont(font)
        self.reset.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius: 15px;\n"
"")
        self.reset.setObjectName("reset")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_2.setGeometry(QtCore.QRect(170, 200, 121, 41))
        self.textBrowser_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #FE9A12;\n"
"border-radius: 15px;\n"
"")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.height = QtWidgets.QLineEdit(self.widget)
        self.height.setGeometry(QtCore.QRect(380, 130, 75, 30))
        self.height.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 170, 127);\n"
"border-radius: 15px;\n"
"")
        self.height.setObjectName("height")
        self.ok = QtWidgets.QPushButton(self.widget)
        self.ok.setGeometry(QtCore.QRect(600, 20, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ok.setFont(font)
        self.ok.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius: 15px;\n"
"")
        self.ok.setObjectName("ok")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 711, 551))
        self.widget_2.setStyleSheet("background-image: url(\'./old1.jpg\');\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.widget_2.raise_()
        self.close.raise_()
        self.analysis.raise_()
        self.textBrowser_3.raise_()
        self.weight.raise_()
        self.lcd.raise_()
        self.textBrowser.raise_()
        self.reset.raise_()
        self.textBrowser_2.raise_()
        self.height.raise_()
        self.ok.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BMI计算器"))
        self.analysis.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">欢迎使用BMI计算器</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">BMI</span></p></body></html>"))
        self.weight.setText(_translate("Form", "63"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">身高(m)</span></p></body></html>"))
        self.reset.setText(_translate("Form", "重置"))
        self.textBrowser_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">体重(kg)</span></p></body></html>"))
        self.height.setText(_translate("Form", "1.75"))
        self.ok.setText(_translate("Form", "计算"))
