# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youth.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(738, 561)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(60, 40, 101, 61))
        self.textBrowser.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt \"华文楷体\";")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(250, 40, 111, 61))
        self.textBrowser_2.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt \"华文楷体\";")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_3.setGeometry(QtCore.QRect(440, 40, 111, 61))
        self.textBrowser_3.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt \"华文楷体\";")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(70, 120, 80, 40))
        self.textEdit.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_4 = QtWidgets.QTextEdit(Form)
        self.textEdit_4.setGeometry(QtCore.QRect(70, 180, 80, 40))
        self.textEdit_4.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_7 = QtWidgets.QTextEdit(Form)
        self.textEdit_7.setGeometry(QtCore.QRect(70, 240, 80, 40))
        self.textEdit_7.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.textEdit_7.setObjectName("textEdit_7")
        self.textEdit_10 = QtWidgets.QTextEdit(Form)
        self.textEdit_10.setGeometry(QtCore.QRect(70, 300, 80, 40))
        self.textEdit_10.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.textEdit_10.setObjectName("textEdit_10")
        self.textEdit_13 = QtWidgets.QTextEdit(Form)
        self.textEdit_13.setGeometry(QtCore.QRect(70, 360, 80, 40))
        self.textEdit_13.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.textEdit_13.setObjectName("textEdit_13")
        self.textEdit_17 = QtWidgets.QTextEdit(Form)
        self.textEdit_17.setGeometry(QtCore.QRect(70, 420, 80, 40))
        self.textEdit_17.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.textEdit_17.setObjectName("textEdit_17")
        self.textEdit_20 = QtWidgets.QTextEdit(Form)
        self.textEdit_20.setGeometry(QtCore.QRect(70, 480, 80, 40))
        self.textEdit_20.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.textEdit_20.setObjectName("textEdit_20")
        self.g_1 = QtWidgets.QLineEdit(Form)
        self.g_1.setGeometry(QtCore.QRect(270, 130, 75, 30))
        self.g_1.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 0);")
        self.g_1.setObjectName("g_1")
        self.g_2 = QtWidgets.QLineEdit(Form)
        self.g_2.setGeometry(QtCore.QRect(270, 190, 75, 30))
        self.g_2.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 0);")
        self.g_2.setObjectName("g_2")
        self.g_3 = QtWidgets.QLineEdit(Form)
        self.g_3.setGeometry(QtCore.QRect(270, 250, 75, 30))
        self.g_3.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 0);")
        self.g_3.setObjectName("g_3")
        self.g_4 = QtWidgets.QLineEdit(Form)
        self.g_4.setGeometry(QtCore.QRect(270, 310, 75, 30))
        self.g_4.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 0);")
        self.g_4.setObjectName("g_4")
        self.g_5 = QtWidgets.QLineEdit(Form)
        self.g_5.setGeometry(QtCore.QRect(270, 370, 75, 30))
        self.g_5.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 0);")
        self.g_5.setObjectName("g_5")
        self.g_6 = QtWidgets.QLineEdit(Form)
        self.g_6.setGeometry(QtCore.QRect(270, 430, 75, 30))
        self.g_6.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 0);")
        self.g_6.setObjectName("g_6")
        self.g_7 = QtWidgets.QLineEdit(Form)
        self.g_7.setGeometry(QtCore.QRect(270, 490, 75, 30))
        self.g_7.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(211, 211, 211);\n"
"color: rgb(0, 0, 0);")
        self.g_7.setObjectName("g_7")
        self.c_1 = QtWidgets.QSpinBox(Form)
        self.c_1.setGeometry(QtCore.QRect(460, 130, 60, 40))
        self.c_1.setStyleSheet("border-radius: 10px;\n"
"background-color:rgb(170, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Agency FB\";\n"
"")
        self.c_1.setObjectName("c_1")
        self.c_2 = QtWidgets.QSpinBox(Form)
        self.c_2.setGeometry(QtCore.QRect(460, 190, 60, 40))
        self.c_2.setStyleSheet("border-radius: 10px;\n"
"background-color:rgb(170, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Agency FB\";\n"
"")
        self.c_2.setObjectName("c_2")
        self.c_3 = QtWidgets.QSpinBox(Form)
        self.c_3.setGeometry(QtCore.QRect(460, 250, 60, 40))
        self.c_3.setStyleSheet("border-radius: 10px;\n"
"background-color:rgb(170, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Agency FB\";\n"
"")
        self.c_3.setObjectName("c_3")
        self.c_4 = QtWidgets.QSpinBox(Form)
        self.c_4.setGeometry(QtCore.QRect(460, 310, 60, 40))
        self.c_4.setStyleSheet("border-radius: 10px;\n"
"background-color:rgb(170, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Agency FB\";\n"
"")
        self.c_4.setObjectName("c_4")
        self.c_5 = QtWidgets.QSpinBox(Form)
        self.c_5.setGeometry(QtCore.QRect(460, 370, 60, 40))
        self.c_5.setStyleSheet("border-radius: 10px;\n"
"background-color:rgb(170, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Agency FB\";\n"
"")
        self.c_5.setObjectName("c_5")
        self.c_6 = QtWidgets.QSpinBox(Form)
        self.c_6.setGeometry(QtCore.QRect(460, 430, 60, 40))
        self.c_6.setStyleSheet("border-radius: 10px;\n"
"background-color:rgb(170, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Agency FB\";\n"
"")
        self.c_6.setObjectName("c_6")
        self.c_7 = QtWidgets.QSpinBox(Form)
        self.c_7.setGeometry(QtCore.QRect(460, 490, 60, 40))
        self.c_7.setStyleSheet("border-radius: 10px;\n"
"background-color:rgb(170, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Agency FB\";\n"
"")
        self.c_7.setObjectName("c_7")
        self.final_grade = QtWidgets.QLCDNumber(Form)
        self.final_grade.setGeometry(QtCore.QRect(610, 40, 81, 61))
        self.final_grade.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.final_grade.setObjectName("final_grade")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 741, 531))
        self.widget.setStyleSheet("\n"
"border-radius: 25px;")
        self.widget.setObjectName("widget")
        self.close = QtWidgets.QPushButton(self.widget)
        self.close.setGeometry(QtCore.QRect(10, 10, 21, 21))
        self.close.setStyleSheet("background-color: #F16C61;\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px; ")
        self.close.setText("")
        self.close.setObjectName("close")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 711, 541))
        self.widget_2.setStyleSheet("background-image : url(\'./youth1.jpg\');\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.reset = QtWidgets.QPushButton(self.widget_2)
        self.reset.setGeometry(QtCore.QRect(610, 410, 81, 41))
        self.reset.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"楷体\";")
        self.reset.setObjectName("reset")
        self.ok = QtWidgets.QPushButton(self.widget_2)
        self.ok.setGeometry(QtCore.QRect(610, 460, 81, 41))
        self.ok.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 15pt \"华文楷体\";")
        self.ok.setObjectName("ok")
        self.widget_2.raise_()
        self.close.raise_()
        self.widget.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()
        self.textBrowser_3.raise_()
        self.textEdit.raise_()
        self.textEdit_4.raise_()
        self.textEdit_7.raise_()
        self.textEdit_10.raise_()
        self.textEdit_13.raise_()
        self.textEdit_17.raise_()
        self.textEdit_20.raise_()
        self.g_1.raise_()
        self.g_2.raise_()
        self.g_3.raise_()
        self.g_4.raise_()
        self.g_5.raise_()
        self.g_6.raise_()
        self.g_7.raise_()
        self.c_1.raise_()
        self.c_2.raise_()
        self.c_3.raise_()
        self.c_4.raise_()
        self.c_5.raise_()
        self.c_6.raise_()
        self.c_7.raise_()
        self.final_grade.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "绩点计算器"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'华文楷体\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'楷体\'; font-size:12pt; font-weight:600;\">课程</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'华文楷体\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'楷体\'; font-size:12pt; font-weight:600;\">成绩</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'华文楷体\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'楷体\'; font-size:12pt; font-weight:600;\">学分(课时)</span></p></body></html>"))
        self.g_1.setText(_translate("Form", "0"))
        self.g_2.setText(_translate("Form", "0"))
        self.g_3.setText(_translate("Form", "0"))
        self.g_4.setText(_translate("Form", "0"))
        self.g_5.setText(_translate("Form", "0"))
        self.g_6.setText(_translate("Form", "0"))
        self.g_7.setText(_translate("Form", "0"))
        self.reset.setText(_translate("Form", "重置"))
        self.ok.setText(_translate("Form", "计算"))
